name: CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Example
      run: cargo build --example google_search_example
      env:
          API_KEY: ${{secrets.API_KEY}}
    - name: Run tests
      run: cargo test --verbose
      env:
          API_KEY: ${{secrets.API_KEY}}

    
